BEGIN;
CREATE TABLE a_users(
	id SERIAL PRIMARY KEY,
	login VARCHAR(20) NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL,
	admin BOOLEAN NOT NULL DEFAULT FALSE,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL
);

CREATE TABLE a_polls(
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL UNIQUE,
	description TEXT
);

CREATE TABLE a_poll_options(
	id SERIAL PRIMARY KEY,
	polls_id INTEGER NOT NULL REFERENCES a_polls (id) ON UPDATE CASCADE ON DELETE CASCADE,
	name VARCHAR(50) NOT NULL,
	description TEXT
);

CREATE TABLE a_votes(
	id SERIAL PRIMARY KEY,
	polls_id INTEGER NOT NULL REFERENCES a_polls (id) ON UPDATE CASCADE ON DELETE RESTRICT,
	poll_options_id INTEGER NOT NULL REFERENCES a_poll_options (id) ON UPDATE CASCADE ON DELETE RESTRICT,
	time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE a_users_polls(
	users_id INTEGER NOT NULL REFERENCES a_users (id) ON UPDATE CASCADE ON DELETE CASCADE,
	polls_id INTEGER NOT NULL REFERENCES a_polls (id) ON UPDATE CASCADE ON DELETE RESTRICT,
	voted BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY (users_id, polls_id)
);
COMMIT;
