BEGIN;
DROP TABLE IF EXISTS a_users CASCADE;
DROP TABLE IF EXISTS a_polls CASCADE;
DROP TABLE IF EXISTS a_poll_options CASCADE;
DROP TABLE IF EXISTS a_votes CASCADE;
DROP TABLE IF EXISTS a_users_polls CASCADE;
COMMIT;
